# Generated by Django 2.2.3 on 2019-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('val', models.CharField(max_length=255)),
            ],
        ),
    ]
